#include <iostream>
using namespace std;
int main() {

	int mush = 20;
	cout << "mush" << mush << endl;
	int number = 10;
	cout << "number" << number << endl;
	int members = 27;
	cout << "member" << members << endl;
	int car = 50;
	cout << "car" << car << endl;
	int dota = 300;
	cout << "dota" << dota << endl;
	short minutes = 60;
	cout << "minutes" <<minutes<< endl;
	short cup = 210;
	cout << "cup" <<cup<< endl;
	short mom = 0;
	cout << "mom" <<mom<< endl;
	short peace = 100;
	cout << "peace" <<peace<< endl;
	short wall = 4;
	cout << "wall" <<wall<< endl;
	float time = 13.2;
	cout << "time" <<time<< endl;
	float size = 15.9;
	cout << "size" <<size<< endl;
	float procent = 80.4;
	cout << "procent" <<procent<< endl;
	float size1 = 19.8;
	cout << "size1" <<size1<< endl;
	float time1 = 20.1;
	cout << "time1" << time1 << endl;
	double grechka = 2131.231;
	cout << "grechka" << grechka << endl;
	double muka = 412.52335;
	cout << "muka" <<muka<< endl;
	double manka = 78243.24234;
	cout << "manka" <<manka<< endl;
	double tsezar = 4825.582;
	cout << "tsezar" <<tsezar<< endl;
	double mouse = 1053.1056;
	cout << "nouse" <<mouse<< endl;
	bool jar = 1;
	cout << "jar" <<jar<< endl;
	bool sara = 0;
	cout << "sara" <<sara<< endl;
	bool bor = 1;
	cout << "bor" <<bor<< endl;
	bool rob = 0;
	cout << "rob" <<rob<< endl;
	bool bob = 0;
	cout << "bob" <<bob<< endl;
	char letter = 'B';
	cout << "letter" <<letter<< endl;
	char sing = '+';
	cout << "sing" <<sing<< endl;
	char number1 = '9';
	cout << "number" <<number1<< endl;
	char pizza = '&';
	cout << "pizza" <<pizza<< endl;
	char symbol = '@';
	cout << "symbol" <<symbol<< endl;
	string name = "Астольфо";
	cout << "name" <<name<< endl;
	string surname = "Белов";
	cout << "surname" <<surname<< endl;
	string city = "London";
	cout << "city" <<city<< endl;
	string Vasay = "Burlakin";
	cout << "Vasay" <<Vasay<< endl;
	string nuhau="Bebra";
	cout << "nuhau" <<nuhau<< endl;
	return 0;
}
